### PR TITLE
Sorts only running containers and pushes them on top of the list

### PR DESCRIPTION
**Pull request by f-cap**
More at: https://github.com/TomasTomecek/sen/issues/76

### CODE REVIEW

**Comment by f-cap** [comment]
There's a little bug I found. When you stop any container then the auto-sorting stops working and after restarting sen everything works well then.

**Comment by TomasTomecek** [comment]
The bug could be resolved easily by sorting `content` here: https://github.com/f-cap/sen/blob/ebb59ac5504132c9fa93a94f973d70e00254eddb/sen/tui/widgets/list/main.py#L163

**Comment by f-cap** [comment]
Now everything should work correctly.

**Comment by TomasTomecek** [comment]
works okay now, thanks a lot for contribution!

**Pull request merged**
