### PR TITLE
Make long line imports to multiline

### PR DESCRIPTION
**Pull request by nagracks**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Is this the preferred style? I like the suggestion, but I don't like the implementation, I would prefer:

```python
from x import (
    # just one tab
    a, b, c
)  # no indentation
```

what do you think? I'm not sure if pylint prefers the style you are proposing.

**Comment by nagracks** [comment]
I don't know but I like it indented two or three tabs rather than one and the closing bracket matching the indentation level.

**Comment by TomasTomecek** [comment]
Sorry for long delays between responses, been busy lately.

I just tried pylint and this is what I get:

```
C: 18, 0: Wrong hanging indentation (remove 8 spaces).
            SelectableText, get_map,
    |       ^ (bad-continuation)
C: 19, 0: Wrong hanging indentation (remove 8 spaces).
            ColorText, UnselectableListBox
    |       ^ (bad-continuation)
C: 20, 0: Wrong hanging indentation.
            )
|   |       ^ (bad-continuation)
```

So please fix indentation to comply with pylint. I will be happy to merge then.

**Comment by nagracks** [comment]
I think now it'll comply with pylint

**Comment by TomasTomecek** [comment]
Indeed so, thank you very much!

**Pull request merged**
