### PR TITLE
this is working fine afaik

### PR DESCRIPTION
**Pull request by akashgosai**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Thank you for another PR! Please show me an example where the existing implementation does not work.

The commit message could also be better.

**Comment by akashgosai** [comment]
This is in response to issue #123

**Comment by TomasTomecek** [comment]
Oh, I haven't realised that at first. Are you actually running into that issue?

As I replied on the original issue, it doesn't cause me problems any more, so I feel that it's not necessary to fix it.

**Comment by akashgosai** [comment]
So it's not merge-able basically?

**Comment by TomasTomecek** [comment]
As I wrote, is the issue I opened a problem for you? Do you run into it? Do you happen to see the same tracebacks as I did?

**Comment by akashgosai** [comment]
no i didn't
i simply wanted to fix that issue

**Comment by TomasTomecek** [comment]
Thank you very much for your help, sorry that you spent time on an invalid issue. If you still have motivation to work on something else, please let me know first and I'll be happy to consult with you.

**Pull request closed without merging**
