### PR TITLE
Add classifiers

### PR DESCRIPTION
**Pull request by hroncok**
Related: #39 

I've added some classifiers. I didn't add Development status, because I'm not sure which one do you feel fits sen.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
You're really awesome. I've set it in PyPI interface but didn't manage to put it to `setup.py`.

I feel like sen is out of beta and is production ready (at least I am using it like that), so this one please:

```
Development Status :: 5 - Production/Stable
```

Do you know when we add this classifier

```
Programming Language :: Python :: 3 :: Only
```

if it makes pip2 to fail the installation?

**Comment by hroncok** [comment]
I don't think it will. You can fail it manually by checking sys.version and raising some exception.

**Comment by hroncok** [comment]
Amended

**Comment by TomasTomecek** [comment]
thank you so much!

**Pull request merged**
